FreeBSD_task:
  matrix:
    env:
      SSL: openssl
    env:
      SSL: openssl111
    env:
      SSL: libressl
    env:
      SSL: libressl-devel
    env:
      SSL:
  matrix:
      image_family: freebsd-12-1-release-amd64
      image_family: freebsd-11-3-snap
  prepare_script:
    - pkg install -y cmake git $SSL
    - git submodule update --init --recursive
  configure_script:
    - ./configure
  build_script:
    - make -j $(sysctl -n hw.ncpu || echo 4) -C tmp
  test_script:
    - ldd build/vpnserver
    - .ci/memory-leak-test.sh
    - .ci/vpntools-check.sh
