.ubuntu: &ubuntu_def
  before_script:
    - REPOSITORY="$PWD" && cd ..
    - apt-get update && apt-get install -y g++ gcc libncurses5-dev libreadline-dev libssl-dev make zlib1g-dev git file
    - wget https://cmake.org/files/v3.12/cmake-3.12.1.tar.gz && tar -xzvf cmake-3.12.1.tar.gz
    - cd cmake-3.12.1 && ./bootstrap && make install
    - cd "$REPOSITORY" && git submodule update --init --recursive
  script:
    - ./configure
    - make package -C tmp

bionic: 
  <<: *ubuntu_def
  image: ubuntu:bionic
  variables:     
    CMAKE: cmake

xenial:     
  <<: *ubuntu_def
  image: ubuntu:xenial
  variables:     
    CMAKE: cmake

trusty:      
  <<: *ubuntu_def
  image: ubuntu:trusty
  variables:     
    CMAKE: cmake3


#
# there's no cmake3 for 12.04
# maybe, there's ppa ?
#
#precise:
#  <<: *ubuntu_def
#  image: ubuntu:precise
#  variables:
#    CMAKE: cmake3

