sudo: required
dist: trusty
os: linux
language: c
compiler:
- gcc
- clang
script:
- "./configure"
- make
deploy:
  provider: launchpad
  slug: "~paskal-07/softether-vpn/+git/SoftEtherVPN"
  oauth_token:
    secure: Pxt8rWxiJ7h2QmTsh5OLuUtW38NuI3G1komTHkBaseNHFQR2GqK9q6hiFeY3Zp7qnbNFJagHZxQdR2umUztsy0JyFLiGgvxQ6BwNx+hJBnXqO186rxa8VpJBWgoaWTIez0ofnghcynDICn2ChcUqLCu0ao+J1Ts/irPB59e7mCU3mh7Z/+7gHfHbN3kO1yGg7phhlMIvjZwLF2pcRx4ak3Py2whnyotVi3SE2C6KBVwt9BUG58dLN6h6PvsQXXWTu/LBhHJ6fB8c4lQn1lgeqn2Qb1Frwk3RO9RQTP65fzh7h9hIBHuScODpY6ZFw0wWcCTfFHTN+3zE0Z48LnV6Hjs7TiNl4fHUkin362R44Ze3syF3Qe273Wul0ll78MEifh+zSKH5MWg7uXV+w7K0BueqQTswhGFmN6Pq3H1yuK1M2zr2Yp4y425Ian7LsnRmmiG8zEFslEfm3ugZiF8YQ9/Lg8agpujj2X5BvW4S5NdesSGFUEqu2tr0NlYep6OKX0BhxOCx+N/882iIbBx6XDuPTdcq6OpUJFk6+hy0UJgznWMGshpgqDZ8wyhw1pIYJblx2FcsGE3d7UgGBDzocJYGVgzMgTC+MM+KmITN6ENe6RMiABGM+RkCal9+/X18RL2E1ClteiRwgFHboQsjM7lsMhXXI4yoUNlqXrnqjn4=
  oauth_token_secret:
    secure: IVU+zByXOOaG/ZmXjL5idkIvxxgPomS5TzDE/uFACFyiKPQcpZe+bbwsYmSOLao9wfNHZ4WbvwVxSNOBWqqrIwSkD38sT5KSPMYfL5yOhu5kb9R4Jckp1FKpEZSQTEgRavEgsmEmadSSuFjA+NKbNUtRn5mI1i9u5y2+MdAgnsQVqAA85eEHa+O/8ulm6GcqbWU0MOrjJfGEawdlSc3qJG1ZzEfEXCUzZ1v0GhG2cansjLRPNxgb9CNWJPwpe+eirdZ4hw0ipe4+1u2UzAdY0PcWIS1bU1OJ8jvwOZuGxMvFRvda19nbL796+5HUvS3BohzEtm+bUERyP//F/hOVTLlLmgJ872IY2Uc4cDrqMglxTg3fb3SBeA+mZMcFy7K9QrrGMpT7xbW2MxlWal4BOgxZica9DRKO4Y5uHUqqfV7lW5qz8nl5jWzVd6dhOCTirNC76D1HR0I3Owm99TmYCMqXf4+M0wjSqZB/pcxy/KOFrBKMcVskI1Lw9tphucnblZzUXbrXfXDzXGO5gfob8UtH5UOGYTlj/EseQLCqysEi56ro5ztS6MTYQARvPTqRaWEdoI2AIeYIBSG8AhoMq6ujIEAt+VJ1uPtE35fGg1xlTeHtAtB3CiCsBIe1N8jjRFHoBYUEFXc0fCg8WfW5Njkg0jPnMvptDEFoIg2Y3xo=
