jobs:
- job: win_64
  displayName: 'Visual Studio 2017'
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    submodules: recursive
  - script: |
     call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      configure
  - script: |
     call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cd tmp
      nmake
